### ISSUE TITLE
Config file unexpected token export

### ISSUE THREAD

**Issue by randohinn** [JeffreyWay/Laravel-Elixir-Rollup#7]
So, I created a `rollup.config.js` file in the project root, with the contents of

``` js
export default {
    entry: 'src/main.js',
    format: 'es2015',
};
```

my Gulpfile looks like this:

``` js
const elixir = require('laravel-elixir'); // eslint-disable-line

elixir((mix) => {
    mix.sass(['main.scss'], 'public/css/foliage.css', './sass');
    mix.rollup('./src/**/*.js', './public/src/foliage.js');
});

```

Upon running elixir, however, I get this error: 

```
E:\Workspace\Webdev\Foliage Native>gulp watch
E:\Workspace\Webdev\Foliage Native\rollup.config.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new RollupTask (E:\Workspace\Webdev\Foliage Native\node_modules\laravel-elixir-rollup-official\dist\RollupTask.js:59:34)
    at Function.<anonymous> (E:\Workspace\Webdev\Foliage Native\node_modules\laravel-elixir-rollup-official\dist\index.js:25:5)
```

What went wrong here?

**Comment by dzava** [comment]
Node doesn't support es6 modules yet. You can change your config to use `module.exports` instead, if you want to import modules you will have to use `require`.

```
module.exports = {
    entry: 'src/main.js',
    format: 'es2015',
};
```

**Comment by faustbrian** [comment]
Currently facing the same issue with the config file, same config as @dzava posted.

```
/project/rollup.config.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at new RollupTask (/project/node_modules/laravel-elixir-rollup-official/dist/RollupTask.js:64:34)
    at Function.<anonymous> (/project/node_modules/laravel-elixir-rollup-official/dist/index.js:25:5)
```
