### ISSUE TITLE
error on usage

### ISSUE THREAD

**Issue by ctf0** [JeffreyWay/Laravel-Elixir-Rollup#9]
- package.json

``` json
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.0",
    "laravel-echo": "^1.0.5",
    "pusher-js": "^3.2.1",
    "vue": "^1.0.26",
    "vue-resource": "^1.0.2",
    "gulp": "^3.9.1",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-rollup-official": "^1.0.2",
    "laravel-elixir-webpack-official": "^1.0.2"
  }
}
```
- gulpfile.js

``` js
// ...

elixir(mix => {
    mix.sass('app.scss').rollup('app.js');
});
```
- error

``` bash
{ SyntaxError: Error transforming /Users/novo/wbs_test/resources/assets/js/bootstrap.js with 'buble' plugin: 'import' and 'export' may only appear at the top level (46:0)
    at Parser.pp$4.raise (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$1.parseStatement (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:715:16)
    at Parser.pp$1.parseBlock (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.parseExprAtom (/Users/novo/wbs_test/node_modules/buble/dist/buble.umd.js:656:26)
    at Parser.pp$3.parseExprSubscripts (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/novo/wbs_test/node_modules/acorn/dist/acorn.js:1637:21)
  pos: 1462,
  loc: Position { line: 46, column: 0 },
  raisedAt: 1468,
  snippet: '42 :  * for events that are broadcast by Laravel. Echo and event broadcasting\n43 :  * allows your team to easily build robust real-time web applications.\n44 :  */\n45 : \n46 : import Echo from "laravel-echo";\n     ^',
  toString: [Function],
  rollupTransform: true,
  id: '/Users/novo/wbs_test/resources/assets/js/bootstrap.js',
  plugin: 'buble' }
```

**Comment by ctf0** [comment]
i now know why i was getting that because `import Echo from "laravel-echo"` which according to `buble` it should be only declared at the very top of the file not where it comes with the default laravel.
